### ISSUE TITLE
Add "types" to package.json

### ISSUE THREAD

**Issue by omichelsen** [sindresorhus/p-limit#16]
Right now the TypeScript definition is not getting picked up.

Adding `"types": "index.d.ts"` to package.json should fix this.

**Comment by sindresorhus** [comment]
TS supports automatically picking up a index.d.ts in root.

**Comment by sindresorhus** [comment]
Either there’s a bug in TS or a problem in your tsconfig.

**Comment by omichelsen** [comment]
Apparently. Will try and figure out why.
