### ISSUE TITLE
Feature request: Ability to clear the queue

### ISSUE THREAD

**Issue by cbwk** [sindresorhus/p-limit#18]
I'm not sure if this is a feature you'd want here, happy to open a PR if so.

In addition to being able to read the values for `activeCount` and `pendingCount`, I would like also to be  able to clear the queue.

The driving use case is that I would like to only run with the latest arguments if there are pending calls.  E.g. I have a function that performs an expensive API based validation, and I only care about the current state of things, not the intermediary state.

Is this a feature that you believe should live here?  Thanks in advance.

**Comment by sindresorhus** [comment]
Sure, sounds useful for when you need more control. PR welcome. Make sure to document some example use-cases.
