### ISSUE TITLE
question: when is memory for each queued function garbage collected?

### ISSUE THREAD

**Issue by stlbucket** [sindresorhus/p-limit#19]
if you put 1000 functions into a queue, will the memory for each be managed along the way or will they all be garbage collected after all promises are resolved?

**Comment by sindresorhus** [comment]
Can you show an example of what you mean? Are you talking about the `limit()` function or the function passed to `limit()`? If the former, it's up to you how long it's stored. If you use `Promise.all()`, it's stored until the end. If the latter, it's released after being called, so along the way.
