### ISSUE TITLE
es5 support for old browsers?

### ISSUE THREAD

**Issue by puzrin** [sindresorhus/p-limit#2]
Package idea is awesome, but i have problem with browserify to es5. Is it official position to drop es5 support or PR will be accepted?

I could suggest 2 things on your choice:

1. Use es5 syntax (i would prefer this way, see no big reasons for es6 here)
2. Add browserify config to package.json:
   ```js
   "browserify": {
     "transform": [
       [
         "babelify",
         {
           "presets": [
             "es2015"
           ]
         }
       ]
     ]
   },
   ```

I'm ready to prepare PR if allowed.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

**Comment by puzrin** [comment]
Sorry for buzz & thanks for the link!
