### ISSUE TITLE
p-limit 2.2.0  can't be accessed by yarn 

### ISSUE THREAD

**Issue by JackZong** [sindresorhus/p-limit#21]
reproduce:
yarn install
yarn.lock
![image](https://user-images.githubusercontent.com/12573233/74143143-34246700-4c35-11ea-8036-fa9b948a9508.png)

then throw error: 405 Method Not Allowed
when I using browser to visit the url: 
https://registry.yarnpkg.com/p-limit/download/p-limit-2.2.0.tgz
Also, return 405 method not allowed.
any ideas? 
Thanks

**Comment by sindresorhus** [comment]
This is not the place to ask for Yarn support => https://github.com/yarnpkg/yarn/issues?q=is:open

**Comment by JackZong** [comment]
> This is not the place to ask for Yarn support => https://github.com/yarnpkg/yarn/issues?q=is:open

could you help to delete this issue, thanks.
