### ISSUE TITLE
Package breaks IE11 unless built

### ISSUE THREAD

**Issue by dcporter** [sindresorhus/p-limit#23]
Since IE11 doesn't support arrow functions or rest/spread, the existing package breaks projects that use it in IE11 if they don't build `node_modules` (a common pattern). This would be resolved if this package were built to target ES5. (Here's [another package](https://github.com/streamich/set-harmonic-interval/pull/4) that ran into this separately.)

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by dcporter** [comment]
> This module mainly targets Node.js, not the browser.

You have the lightest-weight concurrent queue I'm aware of, the browser is a natural market for this package… ;)

Thanks for the `babel-engine-plugin` link. The `engines` field is pretty notoriously misused or forgotten, but I can cross my fingers for no issues…

Having an ES5 build available would solve this perfectly, without special & frankly risky tooling. I understand it's greater-than-zero effort to spin up though. Thanks!
