### ISSUE TITLE
It doesn't seem to finish all tasks if the queue is generated in a for loop

### ISSUE THREAD

**Issue by felixswang** [sindresorhus/p-limit#24]
I'm using the p-limit for limit the concurrence for file writing (about 6k files). The code below works fine:

`
    var writeFilePLimit = pLimit(100);
    var writeFileQueue = [];

    Object.keys(allData).forEach(data => {
      writeFileQueue.push(writeFilePLimit(async () => {
        await fs.promises.writeFile(path, JSON.stringify(data));
      }));
    });
`

However, if I do

`
    var writeFilePLimit = pLimit(100);
    var writeFileQueue = [];

    for (var data in allData) {
      writeFileQueue.push(writeFilePLimit(async () => {
        await fs.promises.writeFile(path, JSON.stringify(data));
      }));
    }
`

then it will only execute 102 files writes (out of 6k files in total). And the 102 files seems to be the first 100 files and the last two files.

I'm not sure whether there is some difference between for loop and Array.forEach() resulted in this. Just want to post this here to see whether I did something wrong. 

Thanks!

**Comment by sindresorhus** [comment]
It would be helpful if you would be able to create a minimal runnable example that reproduces the issue. I can't really do much with just some random code examples. 
Or even better, submit a pull request with one or more [failing tests](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests).

**Comment by shirshak55** [comment]
actually u are relying in clousure property which may not work as expected. have u tried this

```
for (var data in allData) {
  writeFileQueue.push(writeFilePLimit((p,a) =>
fs.promises.writeFile(p, JSON.stringify(a)),
	path,data));
}
```
