### ISSUE TITLE
p-queue vs p-limit

### ISSUE THREAD

**Issue by LiranBri** [sindresorhus/p-limit#3]
Hello,
I would like to understand the different use-cases for using p-queue vs p-limit.

I have a singleton class which fires http requests, it is triggered by different components across my app. I would like to limit the max requests in parallel, and both seems to fit my purpose (even though I find p-limit a nicer approach)

**Comment by LinusU** [comment]
`p-queue` allows having custom queue implementations and defaults to a priority queue so that you would be able to have different priorities on your requests.

`p-limit` is much simpler and does only limit the number of concurrent executions.
