### ISSUE TITLE
Error on try catch block

### ISSUE THREAD

**Issue by ajrsws** [sindresorhus/p-limit#31]
I'm trying to deploy a function to firebase, and looks like one of the packages I use, uses p-limit, and when trying to deploy the function, in the installation modules package the console gives me the following error:

Detailed stack trace: /srv/node_modules/p-limit/index.js:30
                } catch {}

inspecting the p-limit code in my node_modules I see this in line 28

`try {
	await result;
  } catch {}`

there's an error in the catch expression, is missing the parenthesis after catch, **catch(error) {}**

Firebase functions uses node version 8

https://github.com/sindresorhus/p-limit/blob/master/index.js#L30

**Comment by sindresorhus** [comment]
This package requires Node.js 10: https://github.com/sindresorhus/p-limit/blob/824edb836eedc9929ea383457cd82d8367f7322e/package.json#L14

You could downgrade to an older version.

**Comment by 7ochem** [comment]
I have tried this on node 12

**Comment by 7ochem** [comment]
> I have tried this on node 12. Let me check again, just to be sure

Ok it works in node 10 and 12. Sorry for that :smile:
