### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by RyuGuo** [sindresorhus/p-limit#33]
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

./node_modules/_p-limit@3.0.1@p-limit/index.js
Module parse failed: Unexpected token (30:10)
You may need an appropriate loader to handle this file type.
|               try {
|                       await result;
|               } catch {}
|
|               next();

my node vesion is v12.16.1

**Comment by RyuGuo** [comment]
If I change to `catch(e)`, it will throw this error:

> node scripts/build.js

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/_p-limit@3.0.1@p-limit/index.js:4

**Comment by sindresorhus** [comment]
This is a problem with the bundler you use, not this package. Open an issue over there instead.

**Comment by andreidobrinski** [comment]
Hey @RyuGuo, did you find a fix for this?

**Comment by saulpalv** [comment]
this is valid [ES10 syntax](https://www.w3schools.io/javascript/es10-optional-catch-binding/), you need to transpile to es6 with babel

**Comment by saulpalv** [comment]
this is valid [ES10 syntax](https://www.w3schools.io/javascript/es10-optional-catch-binding/), you need to transpile to es6 with babel, because the author has no intention to provide a ES6 code on npm.
