### ISSUE TITLE
ERROR Error loading vue.config.js Error SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by hackftz** [sindresorhus/p-limit#48]
environment: node v8.11.1
use vuecli3 to build front project
[](url)
throw error: node_modules/terser-webpack-plugin/node_modules/p=limit/index.js:29
Unexpected token {
```
} catch {}
```

should use
```
catch(err) { 
 // deal catch error
}
```
![image](https://user-images.githubusercontent.com/33424860/100852956-242a8c00-34c2-11eb-9674-effa2e0d8345.png)

**Comment by sindresorhus** [comment]
You need to upgrade your Node.js version.
