### ISSUE TITLE
should not ignore errors.

### ISSUE THREAD

**Issue by reklatsmasters** [sindresorhus/p-limit#6]
`Promise.all` rejects if any given promise is rejected. I think `p-limit` should follow this standard behavior.

**Comment by dostu** [comment]
p-limit is just for queueing promises. If I understand your suggestion correctly, I don't think it's a good idea. For example, you have an image download queue and one download fails, you don't want to automatically fail all subsequent downloads.

**Comment by offero** [comment]
I think I agree with @reklatsmasters. With the current behavior, Promise.all does not behave as expected.

If someone wants to ignore the errors in their promises, then they should add an explicit .catch to them  that will log and ignore the error.

**Comment by sindresorhus** [comment]
I added to prove that this is no longer an issue in the latest version: https://github.com/sindresorhus/p-limit/commit/f1e6b444870e5d9e3cbfbc298de807f611c88c83
