### ISSUE TITLE
target node or browser or both?

### ISSUE THREAD

**Issue by mesqueeb** [sindresorhus/p-limit#61]
hey!
Does this target node or browser or both?

would love one line in the readme on this!

**Comment by pckilgore** [comment]
Answer: Node (see sindresorhus/p-queue#7)

**Comment by kevlened** [comment]
The only dependency is `yocto-queue`, which has no dependencies, and neither library uses node-specific or browser-specific APIs, so `yocto-queue` is usable in both environments.

**Comment by sindresorhus** [comment]
It works in browsers too.
