### ISSUE TITLE
Vite requires packages to export package.json

### ISSUE THREAD

**Issue by mcmxcdev** [sindresorhus/p-limit#62]
This is the warning created by Vite: 
```
[vite-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
- p-limit
- yocto-queue
```

**Comment by sindresorhus** [comment]
That is a problem with Vite, not this package. That warning is completely wrong. It is not expected that packages export their package.json file. I'm sorry that the Vite project is wasting your time. You should open an issue there instead: https://github.com/vitejs/vite
