### ISSUE TITLE
Error: code: 'ERR_REQUIRE_ESM' in TS

### ISSUE THREAD

**Issue by julianblanco00** [sindresorhus/p-limit#65]
Hi, I have the following code

`import pLimit from 'p-limit'
const limit = pLimit(8)
`

And I receive an error in my console:
`var _pLimit = _interopRequireDefault(require("p-limit"));`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by strowk** [comment]
I am getting this error even by using `import pLimit from 'p-limit';`

**Comment by simplenotezy** [comment]
Same here - can't use p-limit in a nest.js framework

**Comment by simplenotezy** [comment]
Switched to version 3 solves the issue for now

**Comment by TomlDev** [comment]
Same here using v5.
Downgrading to v3 worked.
