### ISSUE TITLE
Module not found: Can't resolve '#async_hooks'

### ISSUE THREAD

**Issue by alaindeurveilher** [sindresorhus/p-limit#72]
Hi,

Since the update of v5.0.0 (updating from 4.0.0) I now get the following error:

```
⨯ ./node_modules/p-limit/index.js:2:0
Module not found: Can't resolve '#async_hooks'
```

My environment is NextJS 14, Node JS 20.8.0

I did not have the issue with pLimit v4.0.0

I see in the [diff between 4.0.0 and 5.0.0](https://github.com/sindresorhus/p-limit/compare/v4.0.0...v5.0.0) a new line for the usage of 
`import {AsyncResource} from '#async_hooks';`

so the error is definitely coming from this update.

I also read a warning on the NodeJS  webpage version 21.1 about the usage of  async_hook: source: https://nodejs.org/api/async_hooks.html

> Async hooks
[Stability: 1](https://nodejs.org/api/documentation.html#stability-index) - Experimental. Please migrate away from this API, if you can. We do not recommend using the [createHook](https://nodejs.org/api/async_hooks.html#async_hookscreatehookcallbacks), [AsyncHook](https://nodejs.org/api/async_hooks.html#class-asynchook), and [executionAsyncResource](https://nodejs.org/api/async_hooks.html#async_hooksexecutionasyncresource) APIs as they have usability issues, safety risks, and performance implications. Async context tracking use cases are better served by the stable [AsyncLocalStorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage) API. If you have a use case for createHook, AsyncHook, or executionAsyncResource beyond the context tracking need solved by [AsyncLocalStorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage) or diagnostics data currently provided by [Diagnostics Channel](https://nodejs.org/api/diagnostics_channel.html), please open an issue at https://github.com/nodejs/node/issues describing your use case so we can create a more purpose-focused API.

Is it safe to be used then? Is this API compatible with node 20 and below ?

Thank you.

**Comment by sindresorhus** [comment]
This is a problem with Next.js. This package is just using [sub-path imports](https://nodejs.org/api/packages.html#subpath-imports). Open an issue on Next.js instead.

**Comment by alaindeurveilher** [comment]
Issue created on Next.js: https://github.com/vercel/next.js/issues/58052

**Comment by andrmoel** [comment]
It is no issue nextjs. We use p-limit is a TypeScript backend project and face the same issue in our unit tests.

**Comment by andrmoel** [comment]
I created a repo to reproduce: https://github.com/andrmoel/async-hooks-test

Description is in the README.md

**Comment by sindresorhus** [comment]
@andrmoel `p-limit` is a ESM module, so you need to use the correct TypeScript config. This has nothing specifically to do with this package.

> Add ["module": "node16", "moduleResolution": "node16"](https://www.typescriptlang.org/tsconfig#module) to your tsconfig.json. ([Example](https://github.com/sindresorhus/tsconfig/blob/main/tsconfig.json))

> - https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm

**Comment by andrmoel** [comment]
@sindresorhus 
It doesn't work. I don't want to make my package a module just because it uses p-limit.

I can add `node16` to my tsconfig but it won't change anything.
PR: https://github.com/andrmoel/async-hooks-test/pull/1
Check the run: https://github.com/andrmoel/async-hooks-test/actions/runs/6769536794/job/18396108036

Please clone my repo and try yourself

**Comment by sindresorhus** [comment]
> I don't want to make my package a module just because it uses p-limit.

Please read: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#pure-esm-package
