### ISSUE TITLE
typescript Module not found: Error: Can't resolve '#async_hooks' in 'F:\workproject\management-service\node_modules\p-limit'

### ISSUE THREAD

**Issue by liangdele** [sindresorhus/p-limit#73]
ERROR in ./node_modules/p-limit/index.js 2:0-43
Module not found: Error: Can't resolve '#async_hooks' in 'F:\workproject\management-service\node_modules\p-limit'
resolve '#async_hooks' in 'F:\workproject\management-service\node_modules\p-limit'
  using description file: F:\workproject\management-service\node_modules\p-limit\package.json (relative path: .)
    resolve as internal import
      using imports field: async_hooks
        Parsed request is a module
        using description file: F:\workproject\management-service\node_modules\p-limit\package.json (relative path: .)
          resolve as module
            F:\workproject\management-service\node_modules\p-limit\node_modules doesn't exist or is not a directory
            F:\workproject\management-service\node_modules\node_modules doesn't exist or is not a directory
            looking for modules in F:\workproject\management-service\node_modules
              single file module
                using description file: F:\workproject\management-service\package.json (relative path: ./node_modules/async_hooks)
                  no extension
                    F:\workproject\management-service\node_modules\async_hooks doesn't exist
                  .tsx
                    F:\workproject\management-service\node_modules\async_hooks.tsx doesn't exist
                  .ts
                    F:\workproject\management-service\node_modules\async_hooks.ts doesn't exist
                  .js
                    F:\workproject\management-service\node_modules\async_hooks.js doesn't exist
              F:\workproject\management-service\node_modules\async_hooks doesn't exist
            F:\workproject\node_modules doesn't exist or is not a directory
            F:\node_modules doesn't exist or is not a directory
 @ ./src/main/nppv-report/app/query/NPPVMultipleDailyReportQuery.ts 20:34-52
 @ ./src/main/nppv-report/NPPVReportModule.ts 20:39-90
 @ ./src/main/main.ts 24:27-68
 @ ./src/index.ts 7:15-37

webpack 5.89.0 compiled with 1 error in 16991 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! manage-service-ts@1.1.18 build: `eslint src --ext .ts && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the manage-service-ts@1.1.18 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2023-11-16T08_34_47_721Z-debug.log

**Comment by sindresorhus** [comment]
This is a problem with Webpack. Open an issue on the Webpack issue tracker instead.
