### ISSUE TITLE
v5 does not work with bunjs: Cannot find package "#async_hooks"

### ISSUE THREAD

**Issue by btakita** [sindresorhus/p-limit#76]
Using the following works with bunjs:

```js
import {AsyncResource} from 'node:async_hooks';
```

**Comment by JonathonRP** [comment]
same issue with deno

**Comment by adxzhang1** [comment]
Also seeing this with esbuild

**Comment by adxzhang1** [comment]
Im also seeing this with esbuild when importing plimit

**Comment by firxworx** [comment]
FYI package imports with `#` prefix are NodeJS subpath imports: https://nodejs.org/api/packages.html#subpath-imports

I reported the following issue earlier which appears related: https://github.com/sindresorhus/p-limit/issues/75
(also see the related issue linked there re nodejs itself)

I honestly wonder a bit how @sindresorhus hasn't hit this issue himself now that it seems like a huge chunk of the ecosystem is impacted!

**Comment by lerman01** [comment]
This issue reproduced also when trying to run typescript apps with [ts-node](https://www.npmjs.com/package/ts-node)

**Comment by jdmarshall** [comment]
https://github.com/oven-sh/bun/pull/3089 seems related

**Comment by GerroDen** [comment]
Same issue with jest and SWC transpilation:
```
no such file or directory, open 'async_hooks'
```

**Comment by harrytran998** [comment]
Hmm - Hope anyone can resolve this soon.

**Comment by elboanas** [comment]
Same for yarn pnp : 

Error: p-limit tried to access #async_hooks, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: #async_hooks (via "#async_hooks\package.json")

**Comment by KubaJastrz** [comment]
Bun has fixed this on their end. Works for me (tested on bun v1.0.30). 

https://github.com/oven-sh/bun/issues/7488

**Comment by jdmarshall** [comment]
@sindresorhus  I think there are a couple duplicates of this issue in the tracker. Heads up.
