### ISSUE TITLE
Limit concurrency of single function

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/p-limit#86]
I have a use case where I have a function that mustn't be running more than x times concurrently because of API restrictions.

I propose the addition of the named export:

```js
function pLimitFunction(function_, concurrency) {
    const limit = pLimit(concurrency);

    return (...arguments_) => limit(() => function_(...arguments_));
}
```

This is similar to #74, except we also define the limiter within the function.

**Comment by sindresorhus** [comment]
Sounds good.

I think the `concurrency` parameter should be an options-object instead.

What about naming it `limitFunction`?

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/p-limit/commit/ef48184a8f9c3d61867d25bebaa8837f23485646
